name: To Do List

on:
  pull_request:
    - main

jobs:
  To-do-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.0

    - name: Run linter
      run: |
        pylint to_do_list/
